# Generated by Django 6.0.3 on 2026-04-19 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comentary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentary',
            new_name='Commentary',
        ),
    ]
